spack:
  definitions:
  - pkgs:
    - gcc@7.3.0
    - cmake
    - fftw+mpi ^openmpi
    - heffte+fftw+cuda cuda_arch=70 ^openmpi
    - accfft ^openmpi
    - openmpi

  view: false
  specs:
  - matrix:
    - [$pkgs]
    - ['%gcc@7.3.0']
    - [arch=x86_64 os=centos7]
