spack:
  definitions:
  - pkgs:
    #- gcc@7.3.0
    #- cmake
    - fftw+mpi
    - heffte+fftw+cuda cuda_arch=70
    - accfft
    - ffte+mpi
    - 2decomp-fft
    #- openmpi

  concretization: together
  view: true
  specs:
  - matrix:
    - [$pkgs]
    - ['%gcc@7.3.0']
    - [arch=x86_64 os=centos7]
