name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, gragghia/ci ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Add an element in this strategy matrix for each FFT library we want to test
    strategy:
      matrix:
        library: [heffte, fftw, accfft, ffte, swfft, 2decomp]
      fail-fast: false
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Build with ${{ matrix.library }}
        run: |
          rm -rf ~/.spack
          source .github/CI/spack_setup.sh
          sload gcc@7.3.0%gcc@4.8.5
          spack compiler find
          spack unload -a
          spack repo add `pwd`/spack/ || true
          #spack env create -d .
          cp .github/CI/spack.yaml .
          spack env activate -d .
          spack add fiber fft=${{ matrix.library }} %gcc@7.3.0
          spack concretize
          spack uninstall -a -y --dependents ${{ matrix.library }} || true
          spack install
          spack load fiber fft=${{ matrix.library }}
          mpirun -n 2 test3D_C2C -lib ${{ matrix.library }} -backend fftw -size 4 4 4 -pgrid 1 2 
        
